export function getPopupUi() {
  return {
    app: document.querySelector(".app"),
    workspace: document.querySelector(".workspace"),
    tokenCompact: document.getElementById("tokenCompact"),
    tokenEditor: document.getElementById("tokenEditor"),
    tokenInput: document.getElementById("tokenInput"),
    tokenHelp: document.getElementById("tokenHelp"),
    saveTokenBtn: document.getElementById("saveTokenBtn"),
    cancelTokenBtn: document.getElementById("cancelTokenBtn"),
    editTokenBtn: document.getElementById("editTokenBtn"),
    captureBtn: document.getElementById("captureBtn"),
    snapshotPickerWrap: document.getElementById("snapshotPickerWrap"),
    snapshotDropdownBtn: document.getElementById("snapshotDropdownBtn"),
    snapshotDropdownLabel: document.getElementById("snapshotDropdownLabel"),
    snapshotDropdownMenu: document.getElementById("snapshotDropdownMenu"),
    examplesPickerWrap: document.getElementById("examplesPickerWrap"),
    examplesDropdownBtn: document.getElementById("examplesDropdownBtn"),
    examplesDropdownLabel: document.getElementById("examplesDropdownLabel"),
    examplesDropdownMenu: document.getElementById("examplesDropdownMenu"),
    snapshotSelect: document.getElementById("snapshotSelect"),
    runBtn: document.getElementById("runBtn"),
    toggleQueryBtn: document.getElementById("toggleQueryBtn"),
    runResultsBtn: document.getElementById("runResultsBtn"),
    examplesSelect: document.getElementById("examplesSelect"),
    formatBtn: document.getElementById("formatBtn"),
    lintBtn: document.getElementById("lintBtn"),
    copyQueryBtn: document.getElementById("copyQueryBtn"),
    copyExportBtn: document.getElementById("copyExportBtn"),
    maxRowsInput: document.getElementById("maxRowsInput"),
    timeoutInput: document.getElementById("timeoutInput"),
    lineNumbers: document.getElementById("lineNumbers"),
    sqlEditor: document.querySelector(".sql-editor"),
    queryInput: document.getElementById("queryInput"),
    statusLine: document.getElementById("statusLine"),
    resultsTable: document.getElementById("resultsTable"),
    resultsHead: document.querySelector("#resultsTable thead"),
    resultsBody: document.querySelector("#resultsTable tbody"),
    jsonOutput: document.getElementById("jsonOutput"),
    jsonPane: document.getElementById("jsonPane"),
    errorsOutput: document.getElementById("errorsOutput"),
    errorsPane: document.getElementById("errorsPane"),
    tablePane: document.getElementById("tablePane"),
    tabTableBtn: document.getElementById("tabTableBtn"),
    tabJsonBtn: document.getElementById("tabJsonBtn"),
    tabErrorsBtn: document.getElementById("tabErrorsBtn"),
    tabButtons: Array.from(document.querySelectorAll("[role='tab']")),
    tabPanes: Array.from(document.querySelectorAll(".tab-pane"))
  };
}
