"""Offline native inspection followed by an explicitly reviewed MarkQL query."""
import markql


html = """
<ul class="catalog">
  <li class="card"><h3>Alpha</h3><p class="price">$10</p></li>
  <li class="card"><h3>Beta</h3><p class="price">$20</p></li>
  <li class="card"><h3>Gamma</h3><p class="price">$30</p></li>
</ul>
"""
document = markql.load(html)
print(markql.inspect(document).to_json())

# This query is hand-written, not generated by a model or by inspect().
query = """
SELECT PROJECT(li) AS (name: TEXT(h3), price: TEXT(p))
FROM doc WHERE attributes.class = 'card'
"""
print(markql.execute(query, doc=document).rows)
